server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    initialization-mode: always
  flyway:
    sql-migration-separator: '_'
    enabled: true
    locations:
      - classpath:/db/migration/ds1/
  jta:
    enabled: true
#    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    atomikos:
      properties:
        enable-logging: true
        log-base-dir: /Users/vivekramachandran/atomikos_logs
      datasource:
        one:
          unique-resource-name: dataSourceOne
          max-pool-size: 5a
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
          xa-properties:
            user: sa
            password:
            URL: jdbc:h2:mem:one
        two:
          unique-resource-name: dataSourceTwo
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
          xa-properties:
            user: sa
            password:
            URL: jdbc:h2:mem:two
        three:
          unique-resource-name: dataSourceThree
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
          xa-properties:
            user: sa
            password:
            URL: jdbc:h2:mem:three;DB_CLOSE_DELAY=-1